# Generated by Django 3.0 on 2019-12-10 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoomService', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='name',
            field=models.CharField(default='Fawwaz', max_length=50),
        ),
    ]
